blank_issues_enabled: false
contact_links:
  - name: Questions & Support
    url: https://github.com/bsekhosana/vanilla-table-enhancer/issues
    about: Ask questions or get help with using Vanilla Table Enhancer

